import { NextRequest, NextResponse } from 'next/server';
import { revalidatePath } from 'next/cache';
import { supabase } from '@/lib/supabase-admin';

const M: Record<string, string> = {
  AUG: 'August 2026', SEP: 'September 2026', OCT: 'October 2026',
  NOV: 'November 2026', DEC: 'December 2026', JAN: 'January 2027',
  FEB: 'February 2027', MAR: 'March 2027', APR: 'April 2027', ARP: 'April 2027',
};

const ESO_ACTIVITIES = [
  // ── KL YOUTH POLICY LAB ─────────────────────────────────────────────
  { code:'KYPL-A01', club_slug:'kl-youth-policy-club', month:M.AUG, title:'KL Youth Policy Lab Orientation & Public Policy Awareness Session', description:'This orientation programme introduces students to the field of public policy, governance, constitutional values, and civic leadership.', competencies:'Policy awareness, Civic literacy, Critical thinking, Communication, Leadership potential, Networking' },
  { code:'KYPL-A02', club_slug:'kl-youth-policy-club', month:M.AUG, title:'Constitution & Governance Workshop', description:'This workshop provides students with an in-depth understanding of the Constitution of India, governance systems, separation of powers, constitutional values, and the functioning of public institutions.', competencies:'Constitutional literacy, Analytical thinking, Research skills, Critical evaluation, Communication, Civic responsibility' },
  { code:'KYPL-A03', club_slug:'kl-youth-policy-club', month:M.OCT, title:'Public Policy Case Study Discussion Series', description:'Students examine real-world public policies implemented by governments in India and across the world.', competencies:'Policy analysis, Evidence-based reasoning, Research skills, Critical thinking, Discussion skills, Problem identification' },
  { code:'KYPL-A04', club_slug:'kl-youth-policy-club', month:M.OCT, title:'Policy Research Methodology Workshop', description:'This workshop equips students with practical skills in policy research, including research design, literature review, survey development, qualitative and quantitative methods, policy evaluation, and report writing.', competencies:'Research design, Data analysis, Report writing, Critical evaluation, Analytical thinking, Academic communication' },
  { code:'KYPL-A05', club_slug:'kl-youth-policy-club', month:M.SEP, title:'Youth Parliament & Legislative Debate', description:'This activity simulates parliamentary proceedings, enabling students to understand legislative processes, democratic debate, policymaking, and parliamentary procedures.', competencies:'Public speaking, Debate skills, Legislative awareness, Leadership, Persuasive communication, Democratic participation' },
  { code:'KYPL-A06', club_slug:'kl-youth-policy-club', month:M.SEP, title:'Policy Analysis Challenge', description:'The Policy Analysis Challenge is a competitive event where students critically examine existing public policies, identify implementation gaps, evaluate outcomes using evidence, and propose practical policy recommendations.', competencies:'Policy evaluation, Critical analysis, Evidence-based reasoning, Problem solving, Written communication, Presentation skills' },
  { code:'KYPL-A07', club_slug:'kl-youth-policy-club', month:M.NOV, title:'Model Legislative Assembly Simulation', description:'This simulation provides students with hands-on experience in legislative governance by replicating the functioning of a state legislative assembly.', competencies:'Legislative processes, Public speaking, Leadership, Teamwork, Decision-making, Civic engagement' },
  { code:'KYPL-A08', club_slug:'kl-youth-policy-club', month:M.NOV, title:'Public Budget & Fiscal Policy Workshop', description:'This workshop introduces students to public finance, government budgeting, taxation, expenditure planning, and fiscal policy.', competencies:'Financial literacy, Analytical thinking, Quantitative reasoning, Policy evaluation, Research skills, Communication' },
  { code:'KYPL-A09', club_slug:'kl-youth-policy-club', month:M.DEC, title:'Governance Innovation Ideathon', description:'The Governance Innovation Ideathon challenges students to develop innovative, technology-enabled, and citizen-centric solutions for public administration and governance.', competencies:'Innovation, Design thinking, Problem solving, Teamwork, Presentation skills, Critical analysis' },
  { code:'KYPL-A10', club_slug:'kl-youth-policy-club', month:M.DEC, title:'Public Administration & Civil Services Seminar', description:'This seminar familiarizes students with careers in public administration, civil services, governance, and policy advisory roles.', competencies:'Career awareness, Goal setting, Communication, Professional development, Analytical thinking, Networking' },
  { code:'KYPL-A11', club_slug:'kl-youth-policy-club', month:M.JAN, title:'SDG Policy Design Competition', description:'The SDG Policy Design Competition challenges students to develop innovative public policies aligned with the United Nations Sustainable Development Goals (SDGs).', competencies:'Sustainable development, Policy design, Research, Innovation, Teamwork, Presentation skills' },
  { code:'KYPL-A12', club_slug:'kl-youth-policy-club', month:M.JAN, title:'Government Officer & Policy Expert Interaction', description:'This interactive session connects students with government officials, policy analysts, legislators, administrators, and governance experts.', competencies:'Networking, Professional communication, Critical inquiry, Career exploration, Policy awareness, Mentorship skills' },
  { code:'KYPL-A13', club_slug:'kl-youth-policy-club', month:M.FEB, title:'Community Policy Consultation Drive', description:'The Community Policy Consultation Drive enables students to engage directly with citizens, local bodies, civil society organizations, and public institutions to identify community needs and gather stakeholder perspectives.', competencies:'Community engagement, Stakeholder consultation, Communication, Research, Empathy, Social responsibility' },
  { code:'KYPL-A14', club_slug:'kl-youth-policy-club', month:M.FEB, title:'Policy Brief Writing Competition', description:'This competition develops students\' ability to communicate complex public policy issues through concise, evidence-based policy briefs.', competencies:'Policy writing, Evidence-based communication, Research synthesis, Academic writing, Critical analysis, Persuasion' },
  { code:'KYPL-A15', club_slug:'kl-youth-policy-club', month:M.FEB, title:'Data-Driven Public Policy Workshop', description:'This workshop introduces students to the use of data analytics in public policy formulation and evaluation.', competencies:'Data analysis, Statistical thinking, Policy evaluation, Digital literacy, Evidence-based reasoning, Research skills' },
  { code:'KYPL-A16', club_slug:'kl-youth-policy-club', month:M.MAR, title:'Civic Leadership & Electoral Literacy Campaign', description:'The Civic Leadership & Electoral Literacy Campaign aims to educate students and communities about democratic values, electoral processes, constitutional rights, responsible citizenship, and informed participation in governance.', competencies:'Civic leadership, Public outreach, Communication, Democratic values, Community engagement, Social responsibility' },
  { code:'KYPL-A17', club_slug:'kl-youth-policy-club', month:M.MAR, title:'Public Policy Hackathon', description:'The Public Policy Hackathon is an intensive innovation event where multidisciplinary student teams collaborate to solve real-world governance and public policy challenges.', competencies:'Innovation, Team collaboration, Problem solving, Design thinking, Time management, Presentation skills' },
  { code:'KYPL-A18', club_slug:'kl-youth-policy-club', month:M.MAR, title:'Inter-University Youth Policy Conclave', description:'The Inter-University Youth Policy Conclave provides a platform for students from multiple institutions to discuss emerging policy issues, exchange ideas, present research, and collaborate on innovative governance solutions.', competencies:'Academic networking, Policy advocacy, Collaboration, Public speaking, Leadership, Research presentation' },
  { code:'KYPL-A19', club_slug:'kl-youth-policy-club', month:M.ARP, title:'Government Institution Study Visit', description:'This experiential learning activity provides students with opportunities to visit government offices, legislative bodies, local self-government institutions, public sector organizations, and administrative agencies to observe governance processes, public service delivery, and policy implementation in practice.', competencies:'Institutional awareness, Observation skills, Research, Communication, Professional conduct, Civic understanding' },
  { code:'KYPL-A20', club_slug:'kl-youth-policy-club', month:M.APR, title:'National Youth Policy Summit (Flagship Event)', description:'The National Youth Policy Summit is the flagship annual event of the KL Youth Policy Lab, bringing together students, policymakers, government officials, researchers, civil society leaders, and industry experts to deliberate on national development priorities, governance reforms, public policy innovation, and sustainable development.', competencies:'Leadership, Policy advocacy, Public speaking, Networking, Event management, Research presentation' },

  // ── SPIRITUAL SCIENCES CLUB ─────────────────────────────────────────
  { code:'SSC-A01', club_slug:'spiritual-sciences-club', month:M.AUG, title:'Spiritual Science Club Orientation & Introduction to Indian Knowledge Systems', description:'This orientation programme introduces students to the vision, mission, objectives, and opportunities offered by the Spiritual Science Club.', competencies:'Self-awareness, Cultural appreciation, Communication, Open-mindedness, Reflective thinking, Community building' },
  { code:'SSC-A02', club_slug:'spiritual-sciences-club', month:M.AUG, title:'Meditation & Mindfulness Practice Workshop', description:'This workshop introduces evidence-based meditation and mindfulness techniques that improve concentration, emotional balance, stress management, and overall well-being.', competencies:'Mindfulness, Stress management, Concentration, Emotional regulation, Self-discipline, Well-being' },
  { code:'SSC-A03', club_slug:'spiritual-sciences-club', month:M.OCT, title:'Yoga Philosophy & Conscious Living Session', description:'This session explores the philosophical foundations of Yoga and its application to modern lifestyles.', competencies:'Philosophical thinking, Self-awareness, Conscious living, Lifestyle awareness, Reflective practice, Communication' },
  { code:'SSC-A04', club_slug:'spiritual-sciences-club', month:M.OCT, title:'Ethics, Values & Character Development Workshop', description:'This workshop focuses on building ethical decision-making, integrity, responsibility, empathy, and professional values through case studies, discussions, and practical scenarios.', competencies:'Ethical reasoning, Integrity, Empathy, Critical thinking, Decision-making, Leadership character' },
  { code:'SSC-A05', club_slug:'spiritual-sciences-club', month:M.SEP, title:'Bhagavad Gita & Universal Wisdom Discussion Circle', description:'This discussion forum examines selected teachings from the Bhagavad Gita and other universal wisdom traditions from a philosophical, ethical, and practical perspective.', competencies:'Philosophical inquiry, Critical analysis, Communication, Ethical thinking, Reflective practice, Cultural literacy' },
  { code:'SSC-A06', club_slug:'spiritual-sciences-club', month:M.SEP, title:'Science of Meditation Seminar', description:'This seminar explores the scientific foundations of meditation by integrating insights from neuroscience, psychology, physiology, and cognitive science.', competencies:'Scientific awareness, Analytical thinking, Interdisciplinary thinking, Critical evaluation, Communication, Research skills' },
  { code:'SSC-A07', club_slug:'spiritual-sciences-club', month:M.NOV, title:'Spiritual Literature Reading Challenge', description:'This reading challenge encourages students to explore classical and contemporary spiritual literature from diverse traditions.', competencies:'Reading comprehension, Reflective thinking, Cultural awareness, Communication, Critical inquiry, Open-mindedness' },
  { code:'SSC-A08', club_slug:'spiritual-sciences-club', month:M.NOV, title:'Personality Development through Spiritual Intelligence Workshop', description:'This workshop develops spiritual intelligence (SQ) as a foundation for personality development, emotional maturity, ethical leadership, resilience, and meaningful decision-making.', competencies:'Emotional intelligence, Self-awareness, Resilience, Leadership, Decision-making, Personal development' },
  { code:'SSC-A09', club_slug:'spiritual-sciences-club', month:M.DEC, title:'Inspirational Speaker & Spiritual Leader Interaction', description:'This interactive session connects students with renowned spiritual leaders, scholars, researchers, and motivational speakers who share their experiences, leadership journeys, ethical insights, and perspectives on purposeful living, innovation, and service to society.', competencies:'Networking, Communication, Leadership inspiration, Reflective listening, Goal setting, Professional awareness' },
  { code:'SSC-A10', club_slug:'spiritual-sciences-club', month:M.DEC, title:'Stress Management through Mindfulness Workshop', description:'This practical workshop equips students with scientifically supported mindfulness techniques to recognize, manage, and reduce stress in academic, personal, and professional settings.', competencies:'Stress management, Mindfulness, Emotional regulation, Self-care, Resilience, Well-being' },
  { code:'SSC-A11', club_slug:'spiritual-sciences-club', month:M.JAN, title:'Community Service & Compassion Initiative', description:'This initiative encourages students to translate spiritual values into meaningful community service through volunteer activities, social outreach programmes, environmental campaigns, education support, and humanitarian initiatives.', competencies:'Social responsibility, Compassion, Community engagement, Teamwork, Leadership, Volunteerism' },
  { code:'SSC-A12', club_slug:'spiritual-sciences-club', month:M.JAN, title:'Interfaith Dialogue & Cultural Harmony Forum', description:'This forum promotes mutual respect, peaceful coexistence, and cultural harmony by encouraging dialogue among students from diverse religious, cultural, and philosophical backgrounds.', competencies:'Intercultural communication, Open-mindedness, Empathy, Active listening, Conflict resolution, Diversity appreciation' },
  { code:'SSC-A13', club_slug:'spiritual-sciences-club', month:M.FEB, title:'Ancient Indian Scientific Knowledge Seminar', description:'This seminar introduces students to the scientific contributions of ancient Indian civilization in fields such as mathematics, astronomy, medicine, metallurgy, architecture, environmental science, and philosophy.', competencies:'Cultural heritage awareness, Research skills, Analytical thinking, Communication, Interdisciplinary knowledge, Critical inquiry' },
  { code:'SSC-A14', club_slug:'spiritual-sciences-club', month:M.FEB, title:'Spiritual Essay, Debate & Quiz Competition', description:'This academic competition encourages students to critically explore spiritual science, ethics, philosophy, well-being, and Indian knowledge systems through essays, debates, quizzes, and public speaking.', competencies:'Academic writing, Debate skills, Public speaking, Critical thinking, Research, Competitive discipline' },
  { code:'SSC-A15', club_slug:'spiritual-sciences-club', month:M.FEB, title:'Nature Meditation & Eco-Spirituality Retreat', description:'This experiential retreat integrates mindfulness with environmental awareness by engaging students in meditation, nature walks, ecological observation, and reflective practices.', competencies:'Mindfulness, Environmental awareness, Reflective practice, Ecological consciousness, Well-being, Observation skills' },
  { code:'SSC-A16', club_slug:'spiritual-sciences-club', month:M.MAR, title:'Digital Well-being & Mindful Technology Workshop', description:'This workshop helps students develop healthy and responsible technology habits by promoting digital well-being, mindful use of digital devices, cyber wellness, and work-life balance.', competencies:'Digital literacy, Mindful behaviour, Self-regulation, Well-being, Responsible technology use, Work-life balance' },
  { code:'SSC-A17', club_slug:'spiritual-sciences-club', month:M.MAR, title:'Happiness, Emotional Intelligence & Positive Living Session', description:'This interactive session explores the science of happiness, emotional intelligence, gratitude, optimism, resilience, and positive psychology.', competencies:'Emotional intelligence, Positive psychology, Gratitude, Resilience, Self-awareness, Well-being' },
  { code:'SSC-A18', club_slug:'spiritual-sciences-club', month:M.MAR, title:'Spiritual Research Poster Presentation Competition', description:'This competition encourages students to conduct interdisciplinary research on spirituality, meditation, well-being, ethics, Indian Knowledge Systems, and consciousness studies.', competencies:'Research skills, Academic writing, Poster design, Presentation skills, Critical thinking, Interdisciplinary inquiry' },
  { code:'SSC-A19', club_slug:'spiritual-sciences-club', month:M.ARP, title:'Value-Based Leadership Conclave', description:'This conclave develops ethical and values-driven leadership by bringing together students, academicians, industry experts, social leaders, and spiritual practitioners to discuss leadership, governance, integrity, sustainability, and service-oriented decision-making.', competencies:'Ethical leadership, Values-driven decision-making, Networking, Communication, Community impact, Professional development' },
  { code:'SSC-A20', club_slug:'spiritual-sciences-club', month:M.APR, title:'National Spiritual Science Summit & Wellness Festival (Flagship Event)', description:'The National Spiritual Science Summit & Wellness Festival is the flagship annual event of the Spiritual Science Club, bringing together students, researchers, academicians, healthcare professionals, spiritual leaders, and industry experts.', competencies:'Leadership, Event management, Collaboration, Communication, Well-being promotion, Interdisciplinary thinking' },

  // ── YUVA TOURISM CLUB ───────────────────────────────────────────────
  { code:'YTC-A01', club_slug:'yuva-tourism-club', month:M.AUG, title:'Yuva Tourism Club Orientation & Responsible Tourism Awareness', description:'This orientation programme introduces students to the objectives, structure, and opportunities offered by the Yuva Tourism Club while promoting the principles of responsible, sustainable, and ethical tourism.', competencies:'Tourism awareness, Sustainable thinking, Communication, Networking, Civic responsibility, Leadership potential' },
  { code:'YTC-A02', club_slug:'yuva-tourism-club', month:M.AUG, title:'Heritage Walk & Monument Documentation Drive', description:'Students visit heritage sites, monuments, museums, and historically significant places to document architectural features, historical importance, conservation needs, and tourism potential.', competencies:'Heritage documentation, Observation skills, Research, Photography, Cultural awareness, Communication' },
  { code:'YTC-A03', club_slug:'yuva-tourism-club', month:M.OCT, title:'Local Tourism Destination Exploration Programme', description:'Students explore nearby tourism destinations to understand destination planning, visitor management, accessibility, hospitality services, environmental sustainability, and local economic development.', competencies:'Destination analysis, Observation, Research, Communication, Environmental awareness, Teamwork' },
  { code:'YTC-A04', club_slug:'yuva-tourism-club', month:M.OCT, title:'Sustainable Tourism Workshop', description:'This workshop introduces sustainable tourism models, environmental management practices, climate-conscious tourism, biodiversity conservation, waste management, and responsible destination planning.', competencies:'Sustainable development, Environmental management, Critical thinking, Policy awareness, Analytical skills, Responsible decision-making' },
  { code:'YTC-A05', club_slug:'yuva-tourism-club', month:M.SEP, title:'Travel Photography & Storytelling Challenge', description:'Students capture tourism destinations through photography and visual storytelling while learning destination interpretation, digital content creation, ethical photography, and tourism promotion.', competencies:'Photography, Visual storytelling, Digital content creation, Creativity, Observation, Communication' },
  { code:'YTC-A06', club_slug:'yuva-tourism-club', month:M.SEP, title:'Eco-Tourism & Nature Trail Expedition', description:'The Eco-Tourism & Nature Trail Expedition provides students with experiential learning in biodiversity conservation, protected area management, nature interpretation, and sustainable tourism practices.', competencies:'Eco-tourism awareness, Environmental observation, Conservation ethics, Research, Physical endurance, Teamwork' },
  { code:'YTC-A07', club_slug:'yuva-tourism-club', month:M.NOV, title:'Tourism Quiz & Destination Knowledge Competition', description:'This academic competition enhances students\' knowledge of tourism destinations, world heritage sites, travel geography, tourism policies, hospitality, aviation, and cultural diversity through quizzes, interactive rounds, and destination-based challenges.', competencies:'Tourism knowledge, General awareness, Critical thinking, Teamwork, Quick decision-making, Research' },
  { code:'YTC-A08', club_slug:'yuva-tourism-club', month:M.NOV, title:'Tour Planning & Itinerary Design Workshop', description:'Students learn the complete process of designing professional travel itineraries by considering destination selection, budgeting, logistics, transportation, accommodation, safety, sustainability, and customer satisfaction.', competencies:'Tour planning, Budgeting, Logistics management, Attention to detail, Problem solving, Customer orientation' },
  { code:'YTC-A09', club_slug:'yuva-tourism-club', month:M.DEC, title:'Hospitality & Tourist Communication Skills Workshop', description:'This workshop focuses on professional communication, customer service excellence, hospitality etiquette, intercultural communication, conflict resolution, and tourist assistance.', competencies:'Hospitality skills, Communication, Customer service, Intercultural awareness, Conflict resolution, Professional etiquette' },
  { code:'YTC-A10', club_slug:'yuva-tourism-club', month:M.DEC, title:'Cultural Exchange & Regional Tourism Festival', description:'The Cultural Exchange & Regional Tourism Festival celebrates India\'s cultural diversity through exhibitions, traditional performances, regional cuisines, handicrafts, tourism presentations, and interactive cultural experiences.', competencies:'Cultural awareness, Event participation, Communication, Teamwork, Creativity, Intercultural appreciation' },
  { code:'YTC-A11', club_slug:'yuva-tourism-club', month:M.JAN, title:'Tourism Entrepreneurship Seminar', description:'The Tourism Entrepreneurship Seminar introduces students to business opportunities within the tourism and hospitality sector.', competencies:'Entrepreneurship, Business planning, Innovation, Career awareness, Networking, Communication' },
  { code:'YTC-A12', club_slug:'yuva-tourism-club', month:M.JAN, title:'Travel Blogging & Digital Content Creation Challenge', description:'This activity enables students to create engaging travel blogs, destination reviews, short videos, podcasts, and digital campaigns to promote tourism destinations responsibly.', competencies:'Digital content creation, Travel writing, Creativity, Digital marketing, Communication, Responsible promotion' },
  { code:'YTC-A13', club_slug:'yuva-tourism-club', month:M.FEB, title:'Tourism Industry Expert Talk & Networking Session', description:'The Tourism Industry Expert Talk provides students with direct interaction with professionals from the tourism, hospitality, aviation, hotel, travel, and destination management sectors.', competencies:'Networking, Professional communication, Career exploration, Industry awareness, Critical inquiry, Mentorship' },
  { code:'YTC-A14', club_slug:'yuva-tourism-club', month:M.FEB, title:'Community-Based Rural Tourism Project', description:'Students collaborate with rural communities to identify tourism potential, document local traditions, promote indigenous culture, and recommend sustainable tourism initiatives.', competencies:'Community engagement, Research, Cultural documentation, Sustainable tourism, Teamwork, Social responsibility' },
  { code:'YTC-A15', club_slug:'yuva-tourism-club', month:M.FEB, title:'Tourism Innovation Hackathon', description:'The Tourism Innovation Hackathon challenges students to develop innovative technology-driven solutions for tourism-related problems.', competencies:'Innovation, Design thinking, Problem solving, Teamwork, Presentation skills, Technology application' },
  { code:'YTC-A16', club_slug:'yuva-tourism-club', month:M.MAR, title:'Heritage Conservation Awareness Campaign', description:'The Heritage Conservation Awareness Campaign is designed to promote public awareness about the importance of preserving cultural, historical, and archaeological heritage.', competencies:'Heritage awareness, Public outreach, Communication, Social responsibility, Advocacy, Community engagement' },
  { code:'YTC-A17', club_slug:'yuva-tourism-club', month:M.MAR, title:'Tourism Research Poster & Case Study Competition', description:'This academic activity encourages students to investigate emerging tourism trends, destination management challenges, hospitality practices, tourism policies, and sustainable tourism initiatives.', competencies:'Research, Analytical thinking, Poster design, Presentation skills, Critical evaluation, Academic communication' },
  { code:'YTC-A18', club_slug:'yuva-tourism-club', month:M.MAR, title:'State Tourism Study Tour', description:'The State Tourism Study Tour provides experiential learning through educational visits to major tourism destinations, heritage sites, eco-tourism locations, hospitality establishments, museums, and tourism development projects.', competencies:'Destination exploration, Observation, Research, Experiential learning, Communication, Documentation' },
  { code:'YTC-A19', club_slug:'yuva-tourism-club', month:M.ARP, title:'Inter-University Tourism Conclave', description:'The Inter-University Tourism Conclave brings together students, academicians, tourism professionals, policymakers, researchers, and entrepreneurs to discuss emerging trends, innovations, sustainability practices, and career opportunities in tourism.', competencies:'Academic networking, Policy discussion, Leadership, Public speaking, Research presentation, Collaboration' },
  { code:'YTC-A20', club_slug:'yuva-tourism-club', month:M.APR, title:'National Yuva Tourism Summit & Travel Expo (Flagship Event)', description:'The National Yuva Tourism Summit & Travel Expo serves as the flagship annual event of the Yuva Tourism Club.', competencies:'Event management, Leadership, Teamwork, Communication, Tourism promotion, Professional networking' },
];

export async function POST(req: NextRequest) {
  if (req.headers.get('x-setup-key') !== 'KLSACsetup2026')
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

  const rows = ESO_ACTIVITIES.map(a => ({
    code:          a.code,
    club_slug:     a.club_slug,
    domain:        'ESO',
    title:         a.title,
    description:   a.description,
    competencies:  a.competencies,
    month:         a.month || null,
    week:          'Week 1',
    activity_date: null,
    venue:         null,
    time_slot:     null,
    difficulty:    'Beginner',
  }));

  const { error } = await supabase.from('activities').upsert(rows, { onConflict: 'code' });
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  revalidatePath('/activities');
  revalidatePath('/');
  return NextResponse.json({ success: true, count: rows.length });
}
